### ISSUE TITLE
Re: Bug in iteration_utilities

### ISSUE THREAD

**Issue by MSeifert04** [caltechlibrary/checkit#1]
Hi,

sorry for simply barging in. I'm the author of the `iteration_utilities` library and I have seen that you removed the `iteration_utilities.grouper` usage because of a segmentation fault (https://github.com/caltechlibrary/checkit/commit/785280d39dc32a6ef4e029a39b61ec7be9a3f1c7) . I just wanted to say thank you for using `iteration_utilities` and I'm very sorry that my library had a bug that caused you this inconvenience.

I have investigated the failure and it was indeed a bug in my library. I fixed that bug today and uploaded a new release to PyPI (maybe not available immediately because of caching, but `python -m pip install iteration_utilities==0.10.0` should work in case you use `pip`) and will update the library on `conda` soon-ish. 

I just wanted to let you know that I (probably) fixed the bug in case you want to give `iteration_utilities` another try. And if you ever encounter any issues with `iteration_utilities` or want to provide feedback, feel free to leave a report on my [issue tracker](https://github.com/MSeifert04/iteration_utilities/issues).

Thanks again and I wish you a nice weekend
Michael

PS: Your current `grouper` function should work fine. But in case you ever want a library solution you could also use also [`more_itertools.chunked`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.chunked) or [`toolz.partition_all`](https://toolz.readthedocs.io/en/latest/api.html#toolz.itertoolz.partition_all) as alternatives to `iteration_utilities`.

**Comment by mhucka** [comment]
Hi,

Actually, thank you for barging in :-). All of this is great information. I do apologize for not filing an issue – it was just a time constraint problem. Thank you for solving that bug. If a situation for a similar function arises again, I'll revisit using `iteration_utilities`.

**Comment by MSeifert04** [comment]
Thanks for your answer and I'm sorry for not responding earlier.

It's totally understandable that you haven't filed an issue - I also know the problem of time constraints to well. :-) But if you ever use iteration_utilities again and encounter any problem feel free to file an issue even if it doesn't contain much information, if I have the time I'll investigate it myself.

Thanks again for making me aware of the problem.
